### ISSUE TITLE
Create TRM Preset list, and Template A/C

### ISSUE THREAD

**Issue by daviddcs** [132nd-vWing/132-TRP-388#3]
Pref at the same time we add waypoints at home-plate.

**Comment by 132ndNeck** [comment]
I will look into this in a week when I am back home on a computer with DCS.

**Comment by daviddcs** [comment]
As per Discord.
My only concern is the eventual HAS doors not opening bug.


[f16s to trm.zip](https://github.com/132nd-vWing/132-TRP-388/files/3721590/f16s.to.trm.zip)
![TRM_STUD_F16_B1](https://user-images.githubusercontent.com/20663542/66713656-9f584c80-edad-11e9-9552-e26181a35037.png)

**Comment by 132ndNeck** [comment]
Not valid anymore, and presets are added to ATRM.
