### ISSUE TITLE
Develop TRM MOAs and Ranges to faciliate for 388th TRP

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/132-TRP-388#5]
Develop the TRM to facilitate for 388th TRP.
Intention is to develop MOA and Ranges NORTH of the TMA to facilitate for this.
Will be conducted weekend 18th Oct -20th Oct.

If anyone have any specifics you see that we need, please write it down as comments here.

Features needed:
- Dedicated tanker the Viper

**Comment by 132Ashilta** [comment]
Some points for consideration:
* Will the 388th be based at Kutaisi with everyone else? We're quickly running out of space on the north ramp!
* Do we need to consider the addition of another MOA for air-to-air training, or the division of MOA W into two, smaller MOA? With the 494th, the 388th and the 108th all potentially conducting air-to-air training, we run the risk of running out of space.
* I believe the current ranges are probably appropriate, provided that one is large enough to suitably accommodate TGP training which would also benefit the 494th; Range 3A may be the most appropriate but may require some tailoring

**Comment by 132ndNeck** [comment]
I was thinking of basing the 388th at Senaki, or having some jets at senaki, and some at Kutaisi 
(If we have ATC, then it can also be a challenge for them to handle two airbases within the same TMA).
But having some jets at Kutaisi will also give flexibility to run ops from there if needed.

Yes, I will make some additional MOAs and ranges as we are getting more and more participants.
I will make a new combatflite file, and input the exisiting ones , and find spots for new ones.

All ranges already in place is suitable for all trainings, so that should not be a problem, but I will add additional ones north of Kutaisi/TMA in addition as we are getting more flights.

**Comment by 132ndNeck** [comment]
We have moved to ATRM. Closing this
